import { Pool } from 'pg';
import type { Conversation, StoredMessage, User, UserSettings } from './domain';
import type { FluidRepository } from './repositories';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const mapSettings = (row: Record<string, unknown>): UserSettings => ({ nativeLanguage: row.native_language as UserSettings['nativeLanguage'], translationLanguage: row.translation_language as UserSettings['translationLanguage'], preferredVoice: row.preferred_voice as string, translatedAudioEnabled: row.translated_audio_enabled as boolean, originalCaptionsEnabled: row.original_captions_enabled as boolean, translatedCaptionsEnabled: row.translated_captions_enabled as boolean, originalAudioVolume: Number(row.original_audio_volume ?? .9), translatedAudioVolume: Number(row.translated_audio_volume ?? .75) });

export class PostgresRepository implements FluidRepository {
  async getUser(id: string) { const { rows } = await pool.query('select u.id,u.email,u.display_name,s.* from users u join user_settings s on s.user_id=u.id where u.id=$1', [id]); if (!rows[0]) return null; return { id: rows[0].id, email: rows[0].email, displayName: rows[0].display_name, settings: mapSettings(rows[0]) } as User; }
  async updateSettings(userId: string, patch: Partial<UserSettings>) { const current = await this.getUser(userId); if (!current) throw new Error('User not found'); const next = { ...current.settings, ...patch }; await pool.query('update user_settings set native_language=$2,translation_language=$3,preferred_voice=$4,translated_audio_enabled=$5,original_captions_enabled=$6,translated_captions_enabled=$7,original_audio_volume=$8,translated_audio_volume=$9,updated_at=now() where user_id=$1', [userId,next.nativeLanguage,next.translationLanguage,next.preferredVoice,next.translatedAudioEnabled,next.originalCaptionsEnabled,next.translatedCaptionsEnabled,next.originalAudioVolume,next.translatedAudioVolume]); return { ...current, settings: next }; }
  async getConversation(id: string) { const { rows } = await pool.query('select c.id,c.title,c.kind,c.created_at,array_agg(cm.user_id) member_ids from conversations c join conversation_members cm on cm.conversation_id=c.id where c.id=$1 group by c.id', [id]); if (!rows[0]) return null; return { id: rows[0].id, title: rows[0].title, kind: rows[0].kind, memberIds: rows[0].member_ids, createdAt: rows[0].created_at.toISOString() } as Conversation; }
  async listMessages(conversationId: string, memberId: string) { const allowed = await pool.query('select 1 from conversation_members where conversation_id=$1 and user_id=$2', [conversationId,memberId]); if (!allowed.rowCount) throw new Error('Forbidden'); const { rows } = await pool.query('select m.*,coalesce(json_object_agg(mt.target_language,mt.translated_text) filter(where mt.id is not null),\'{}\') translations from messages m left join message_translations mt on mt.message_id=m.id where m.conversation_id=$1 group by m.id order by m.created_at', [conversationId]); return rows.map(row => ({ id:row.id,conversationId:row.conversation_id,senderId:row.sender_id,originalText:row.original_text,sourceLanguage:row.source_language,createdAt:row.created_at.toISOString(),translations:row.translations })) as StoredMessage[]; }
  async createMessage(message: Omit<StoredMessage,'translations'>) { await pool.query('insert into messages(id,conversation_id,sender_id,original_text,source_language,created_at) values($1,$2,$3,$4,$5,$6)', [message.id,message.conversationId,message.senderId,message.originalText,message.sourceLanguage,message.createdAt]); return { ...message, translations: {} }; }
  async saveTranslation(messageId:string,targetLanguage:string,text:string) { await pool.query('insert into message_translations(id,message_id,target_language,translated_text) values(gen_random_uuid(),$1,$2,$3) on conflict(message_id,target_language) do update set translated_text=excluded.translated_text', [messageId,targetLanguage,text]); }
  async getMessage(id:string) { const { rows } = await pool.query('select m.*,coalesce(json_object_agg(mt.target_language,mt.translated_text) filter(where mt.id is not null),\'{}\') translations from messages m left join message_translations mt on mt.message_id=m.id where m.id=$1 group by m.id',[id]); if (!rows[0]) return null; const row=rows[0]; return {id:row.id,conversationId:row.conversation_id,senderId:row.sender_id,originalText:row.original_text,sourceLanguage:row.source_language,createdAt:row.created_at.toISOString(),translations:row.translations} as StoredMessage; }
}
