-- PostgreSQL production schema. Audio blobs are intentionally absent: Fluid does not retain raw microphone audio by default.
create table users (id uuid primary key, email text unique not null, display_name text not null, created_at timestamptz not null default now());
create extension if not exists pgcrypto;
create table user_settings (user_id uuid primary key references users(id) on delete cascade, native_language text not null, translation_language text not null, preferred_voice text, voice_source text not null default 'fixed' check(voice_source in ('fixed','speaker')), share_my_voice boolean not null default false, translated_audio_enabled boolean not null default true, original_captions_enabled boolean not null default true, translated_captions_enabled boolean not null default true, original_audio_volume numeric not null default .9, translated_audio_volume numeric not null default .75, updated_at timestamptz not null default now());
create table conversations (id uuid primary key, title text, kind text not null check(kind in ('direct','group')), created_at timestamptz not null default now());
create table conversation_members (conversation_id uuid references conversations(id) on delete cascade, user_id uuid references users(id) on delete cascade, joined_at timestamptz not null default now(), primary key(conversation_id,user_id));
create table messages (id uuid primary key, conversation_id uuid not null references conversations(id) on delete cascade, sender_id uuid not null references users(id), original_text text not null, source_language text not null, created_at timestamptz not null default now());
create table message_translations (id uuid primary key, message_id uuid not null references messages(id) on delete cascade, target_language text not null, translated_text text not null, created_at timestamptz not null default now(), unique(message_id,target_language));
create table conversation_invites (id uuid primary key, conversation_id uuid not null references conversations(id) on delete cascade, inviter_id uuid not null references users(id), invitee_id uuid not null references users(id), status text not null check(status in ('pending','accepted','declined','expired')), created_at timestamptz not null default now());
