'use client';
import { useEffect, useRef, useState } from 'react';
import { CallPeer } from '@/lib/webrtc/call';
import { SocketRealtimeClient } from '@/lib/realtime/socket-client';

export function useFluidCall(conversationId: string, userId = 'alex') {
  const [state, setState] = useState<'idle'|'connecting'|'connected'|'reconnecting'|'error'>('idle');
  const [muted, setMuted] = useState(false); const socket = useRef<SocketRealtimeClient | null>(null); const stream = useRef<MediaStream | null>(null); const peers = useRef(new Map<string, CallPeer>()); const recognition = useRef<any>(null);
  useEffect(() => { const client = new SocketRealtimeClient(userId); socket.current = client; client.on('connect', () => client.emit('call:join', { conversationId }, result => setState(result.ok ? 'connected' : 'error'))); client.on('call:error', () => setState('error')); client.on('participant:joined', ({ userId: remoteId }) => void createPeer(remoteId, true)); client.on('webrtc:offer', ({ from, offer }) => void createPeer(from, false, offer)); client.on('webrtc:answer', ({ from, answer }) => void peers.current.get(from)?.receive({ type:'answer', payload:answer })); client.on('webrtc:ice-candidate', ({ from, candidate }) => void peers.current.get(from)?.receive({ type:'ice', payload:candidate })); return () => { recognition.current?.stop(); recognition.current = null; client.emit('call:leave', { conversationId }); peers.current.forEach(peer => peer.close()); stream.current?.getTracks().forEach(track => track.stop()); client.disconnect(); }; // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [conversationId, userId]);
  async function createPeer(remoteId: string, offerer: boolean, incomingOffer?: RTCSessionDescriptionInit) { if (peers.current.has(remoteId)) return; const peer = new CallPeer(event => socket.current?.emit(`webrtc:${event.type === 'ice' ? 'ice-candidate' : event.type}`, { conversationId, targetId: remoteId, [event.type]: event.payload })); peer.connection.ontrack = event => { const audio = new Audio(); audio.autoplay = true; audio.srcObject = event.streams[0]; }; peer.connection.onconnectionstatechange = () => { if (peer.connection.connectionState === 'disconnected') setState('reconnecting'); if (peer.connection.connectionState === 'connected') setState('connected'); }; peers.current.set(remoteId, peer); if (stream.current) await peer.attachLocalStream(stream.current); if (incomingOffer) await peer.receive({ type:'offer', payload:incomingOffer }); else if (offerer) await peer.createOffer(); }
  function startBrowserTranscription() { const Recognition = (window as any).SpeechRecognition ?? (window as any).webkitSpeechRecognition; if (!Recognition || recognition.current) return; const session = new Recognition(); session.lang = 'en-US'; session.interimResults = true; session.continuous = true; session.onstart = () => socket.current?.emit('speech:start', { conversationId }); session.onresult = (event: any) => { const result = event.results[event.results.length - 1]; const text = result[0]?.transcript?.trim(); if (!text) return; socket.current?.emit(result.isFinal ? 'speech:final' : 'speech:partial', { conversationId, text, sourceLanguage: 'en' }); }; session.onerror = () => setState('error'); session.start(); recognition.current = session; }
  async function enableMicrophone() { try { setState('connecting'); stream.current = await navigator.mediaDevices.getUserMedia({ audio: true, video: false }); await Promise.all([...peers.current.values()].map(peer => peer.attachLocalStream(stream.current!))); startBrowserTranscription(); setMuted(false); setState('connected'); } catch { setState('error'); } }
  function toggleMute() { const track = stream.current?.getAudioTracks()[0]; if (!track) return void enableMicrophone(); track.enabled = !track.enabled; setMuted(!track.enabled); }
  return { state, muted, toggleMute, enableMicrophone, socket: socket.current };
}
